pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/Pablo-Carabajal/prueba-con-Jenkings.git'
            }
        }
        stage('Build') {
            steps {
                script {
                    // Cambia al directorio src
                    dir('src') {
                        // Compila el archivo HolaMundo.java
                        sh 'javac HolaMundo.java'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    // Ejecuta el archivo HolaMundo.class
                    dir('src') {
                        sh 'java HolaMundo'
                    }
                }
            }
        }
    }
}
